name: "Terraform eks cluster"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm destroy action'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: Add profile credentials to ~/.aws/credentials
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile palmira-terraform
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile palmira-terraform
        aws configure set region us-east-1 --profile palmira-terraform

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
